FROM registry.access.redhat.com/ubi8/dotnet-60:6.0 as builder
WORKDIR /opt/app-root/src
COPY --chown=1001 . .
RUN dotnet publish -c Release


FROM registry.access.redhat.com/ubi8/dotnet-60:6.0
EXPOSE 8085
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef --version 6.*
ENV ASPNETCORE_URLS=http://*:8085
COPY --from=builder /opt/app-root/src/bin /opt/app-root/src/JOIEnergy/bin
WORKDIR /opt/app-root/src/JOIEnergy/bin/Release/net6.0/publish
CMD ["dotnet", "JOIEnergy.dll"]